"""
Movie Explorer Platform — FastAPI Backend
==========================================
Entry point. Configures:
  - SQLAlchemy database creation and seeding on startup
  - CORS for frontend access
  - OpenAPI / Swagger UI (auto-generated by FastAPI at /api/docs)
  - Route registration for Movies, Actors, Directors, Genres
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from database import engine, SessionLocal
from models import Base
from seed_data import seed_database
from routers import movies, actors, directors, genres


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs on application startup:
    1. Creates all database tables (if they don't exist)
    2. Seeds the database with sample data (if empty)
    """
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        seed_database(db)
    finally:
        db.close()
    yield  # Application runs here
    # Shutdown logic (if needed) goes after yield


app = FastAPI(
    title="Movie Explorer API",
    description=(
        "A RESTful API for browsing movies, actors, directors, and genres.\n\n"
        "## Features\n"
        "- Browse and filter movies by genre, director, actor, or release year\n"
        "- View actor and director profiles with their full filmographies\n"
        "- All filtering is handled server-side\n\n"
        "## Notes\n"
        "- Movie ratings are out of 10\n"
        "- Filter parameters can be combined freely\n"
        "- Returns 404 with a clear error message for invalid IDs\n"
    ),
    version="1.0.0",
    docs_url="/api/docs",       # Swagger UI
    redoc_url="/api/redoc",     # ReDoc UI
    openapi_url="/api/openapi.json",
    lifespan=lifespan,
)

# Allow requests from the React frontend (dev and production)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173", "*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register routers
app.include_router(movies.router)
app.include_router(actors.router)
app.include_router(directors.router)
app.include_router(genres.router)


@app.get("/api/health", tags=["Health"])
def health_check():
    """Health check endpoint. Returns 200 when the API is running."""
    return {"status": "ok", "message": "Movie Explorer API is running"}
